trigger:
  branches:
    include:
      - master 

pool:
  name: 'adarsh' 

variables:
- group: tfcloud    
- name: TF_WORKING_DIR
  value: '.'
- name: TF_CLOUD_ORG
  value: 'azure-devops-infra'
- name: TF_CLOUD_WORKSPACE
  value: 'Azure_devOps-AKS-infra-terraformCloud'
    

stages:
  - stage: infra
    displayName: "Provision All Resources"
    jobs:
      - job: terraformJob
        displayName: "Terraform Apply"
        steps:
          - checkout: self
          
          - task: AzureCLI@2
            displayName: 'Terraform Init (Terraform Cloud)'
            inputs:
              azureSubscription: 'AzureARM'        # <-- use actual connection name
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              workingDirectory: '$(TF_WORKING_DIR)'
              inlineScript: |
                echo "Initializing Terraform Cloud backend..."
                terraform init -input=false
            env:
              TF_TOKEN_app_terraform_io: $(terraformToken)

          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(TF_WORKING_DIR)'
              environmentServiceNameAzureRM: 'AzureARM'   # <-- use actual connection name

          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(TF_WORKING_DIR)'
              environmentServiceNameAzureRM: 'AzureARM'   # <-- use actual connection name

